import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from "../components/navbar/navbar";
import {useState} from "react";
import HomeTab from "../components/tabs/home-tab";
import PlcTab from "../components/tabs/plc-tab";
import Script from 'next/script'

const Home: NextPage = () => {
    const [activeTab, setActiveTab] = useState(0)
    const [activeRun, setActiveRun] = useState(true)

    return (
        <div>
            <Head>
                <title>Virtual Laboratory</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <Script src="/public/static/js/aframe.min.js"></Script>
                <Script src="/public/static/js/aframe-ar.js"></Script>
                <Script src="https://cdn.jsdelivr.net/npm/aframe-aabb-collider-component@3.2.0/dist/aframe-aabb-collider-component.min.js"></Script>

            </Head>
            <div className={'absolute top-0 w-full z-10'}>
                <Navbar activateTab={setActiveTab}  activeTab={activeTab}/>
            </div>
            <div className={''}>
                {activeTab ==- 0 ? <HomeTab activeRun={activeRun}/> :
                        <PlcTab activateRun={setActiveRun} activeRun={activeRun}/>
                }
            </div>
        </div>
    )
}

export default Home
